### ISSUE TITLE
gulp-coffee won't compile after an error occured(and handled) when used with gulp-watch

### ISSUE THREAD

**Issue by Foolyou** [contra/gulp-coffee#68]
My gulpfile:
```
var gulp = require('gulp');
var gutil = require('gulp-util');
var watch = require('gulp-watch');
var coffee = require('gulp-coffee');
gulp.task('watch', function () {
  var src = ...;
  var dest = ...;
  return gulp.src(src)
               .pipe(watch(src).on(change, gutil.log))
               .pipe(coffee().on('error', gutil.log))
               .pipe(gulp.dest(dest));
});
```
I used <code>gulp watch</code>, and wrote a coffee file which was then compiled. Then I made a syntax error in that coffee file, so gulp logged an error. Gulp still logged file changes when I fixed that syntax error & saved, however coffee file was not compiled again.

**Comment by contra** [comment]
Are you using gulp 4? The watcher is redone, you should try that

**Comment by Foolyou** [comment]
Thanks @contra.

Do you mean with `gulp 4` which uses `chokidar`, we do not need `gulp-watch` any more?

I'm considering temporarily use `gulp-changed` with `gulp-watch` to avoid this issue, and test `gulp 4` with my huge old gulpfile.

**Comment by Foolyou** [comment]
Ah, found the way.

```
gulp.task('watch', function (done) {
  var src = ...;
  var dest = ...;
  return gulp.src(src)
               .pipe(watch(src).on(change, gutil.log))
               .pipe(coffee().on('error', function (p) {
                 gutil.log(p);
                 done(); 
               }))
               .pipe(gulp.dest(dest));
});
```

**Comment by BirgitPohl** [comment]
@contra I stepped over this issue. With my file watcher I need to restart my gulp task. Can you tell me more about the watcher in Gulp 4? I'm currently using 3.9.1.
