### ISSUE TITLE
do sourcemaps still work?

### ISSUE THREAD

**Issue by hildjj** [contra/gulp-coffee#70]
I'm copy/pasting the example from the readme, and am not getting sourcemaps in my output directory.  Any hints to debug?

**Comment by hildjj** [comment]
It works when I specify `sourcemaps.write('.')` instead of `sourcemaps.write())`.  Please change the docs or the implementation to match.

**Comment by contra** [comment]
`sourcemaps.write()` should write an inline sourcemap as a comment, `sourcemaps.write('.')` should make a new .coffee.map file

**Comment by hildjj** [comment]
Oh! Sorry about that.
