### ISSUE TITLE
Update coffee-script dependency

### ISSUE THREAD

**Issue by pmb0** [contra/gulp-coffee#74]
Please release new version of gulp-coffee with included coffee-script 1.10.0 dependency.

**Comment by contra** [comment]
PR?

**Comment by pmb0** [comment]
You already updated it in [master](https://github.com/contra/gulp-coffee/blob/master/package.json#L13), but is not released yet. [v2.3.1](https://github.com/contra/gulp-coffee/blob/v2.3.1/package.json#L13) is missing coffee-script v1.10.0.
