### ISSUE TITLE
Cofeescript2 support?

### ISSUE THREAD

**Issue by objectkit** [contra/gulp-coffee#78]
Great to see the recent changes to ``includes``... any plans for [CoffeeScript 2](http://coffeescript.org/announcing-coffeescript-2/) support here?

**Comment by contra** [comment]
Did the API change? Otherwise you should be able to update your coffee version and it will work fine

**Comment by objectkit** [comment]
Do you mean the CoffeeScript API? The package.json here is dependent on CoffeeScript 1.10.0 in ``node_modules/coffee-script``, whereas the CoffeeScript 2.0.0 convention installs to ``node_modules/coffeescript``. Gulp-coffee seems to be using the 1.10.0 edition, transpiling to ECMAScript 5, rather than picking up on the 2.0 installation which transpiles to ECMAScript 6... unless I'm missing something myself...

**Comment by contra** [comment]
@objectkit I'll keep this open to update the dep here https://github.com/contra/gulp-coffee/blob/master/package.json#L13

I'll update it to 2.0 and bump this package to 2.0 as well

**Comment by objectkit** [comment]
@contra Great stuff 👍

**Comment by contra** [comment]
Published as 3.0
