### ISSUE TITLE
Remove lock files

### ISSUE THREAD

**Issue by demurgos** [contra/gulp-coffee#82]
Hi,
I see that your library is using lock files but I believe that you should avoid it.
Lock files are great to get reproducible builds for applications (top level packages) but should be avoided in libraries (non top level packages) because it prevents CI to automatically get the latest version of the dependencies: devs have to update it manually. This is a problem because lock files are not used for library consumers. It means that consumers are always the first to be affected by breakage in transitive dependencies while it would be better to catch it in your own CI.

**Comment by demurgos** [comment]
Hi, I just got the notification. It may come a bit late but I just wanted to add there does not seem to be a consensus about lock files for libraries. I usually used them but discussed recently with some maintainers that recommend the opposite the reasons I explained above.
I see that you decided to remove it, but please also check the pros and cons. I am currently trying both styles for my libraries so I'm also interested by your feedback.

**Comment by contra** [comment]
I usually remove them, sometimes I don't care enough one way or the other and will publish one. I'll continue removing them in the future, mostly just to clear up annoying diffs.
